# NumPy Basics

NumPy, abreviado de Numerical Python, es uno de los paquetes fundamentales más importantes para la computación numérica en Python. Muchos paquetes computacionales que ofrecen funcionalidad científica utilizan los objetos de arrays de NumPy como una de las interfaces estándar de intercambio de datos. Gran parte del conocimiento sobre NumPy que cubro también es aplicable a pandas.

In [10]:
import numpy as np

In [11]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [12]:
%timeit my_arr2 = my_arr * 2

1.99 ms ± 328 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
%timeit my_list2 = [x *2 for x in my_list]

82.1 ms ± 5.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Los algoritmos basados en NumPy generalmente son de 10 a 100 veces más rápidos (o incluso más) que sus equivalentes en Python puro, y utilizan significativamente menos memoria.

## Multidimensional Array Object

`np.array` es una clase fundamental en la biblioteca NumPy (Numerical Python) que proporciona una estructura de datos llamada "ndarray" (arreglo multidimensional) para el almacenamiento y manipulación eficiente de datos numéricos en Python. Los arreglos de NumPy son similares a las listas de Python, pero ofrecen muchas ventajas adicionales, como operaciones vectorizadas, acceso rápido a elementos y una mayor eficiencia en términos de memoria y rendimiento.

Aquí hay algunos aspectos importantes para tener en cuenta sobre `np.array`:

1. Creación de arreglos:
   - Puedes crear un ndarray utilizando funciones como `np.array()`, `np.zeros()`, `np.ones()`, `np.empty()`, `np.arange()`, `np.linspace()`, entre otras.

2. Dimensionalidad:
   - Los arreglos de NumPy pueden ser unidimensionales (vectores), bidimensionales (matrices) o tener más dimensiones.

3. Propiedades del arreglo:
   - `shape`: Devuelve una tupla que indica el tamaño de cada dimensión del arreglo.
   - `dtype`: Especifica el tipo de datos de los elementos almacenados en el arreglo.

4. Operaciones vectorizadas:
   - Las operaciones en arreglos de NumPy se aplican de forma vectorizada, lo que permite realizar operaciones rápidas y eficientes en grandes conjuntos de datos.

5. Indexación y rebanado:
   - Los arreglos de NumPy admiten una variedad de técnicas de indexación y rebanado para acceder y modificar elementos y subconjuntos de datos.

6. Operaciones matemáticas:
   - NumPy ofrece una amplia gama de funciones matemáticas y operadores para realizar cálculos en arreglos, como suma, resta, multiplicación, división, exponenciación y más.

7. Broadcasting:
   - NumPy permite realizar operaciones entre arreglos de diferentes tamaños a través del broadcasting, que es una regla para extender automáticamente las dimensiones de los arreglos más pequeños para que coincidan con los más grandes.

8. Eficiencia:
   - Debido a que los arreglos de NumPy están implementados en C y utilizan tipos de datos nativos, son más eficientes en términos de memoria y rendimiento en comparación con las listas de Python.

9. Integración con otras bibliotecas:
   - NumPy es ampliamente utilizado en la comunidad científica y es una base para muchas otras bibliotecas populares, como SciPy, pandas y scikit-learn.

En resumen, `np.array` es una poderosa herramienta para trabajar con datos numéricos en Python, y su uso es esencial para realizar cálculos eficientes y manipulación de datos en aplicaciones científicas, matemáticas y de análisis de datos.


In [17]:
data = np.array([[1,2,3],[4,5,6]])
other_array = np.array([[10, 20, 30], [40, 50, 60]])

Podemos hacer operaciones matemáticas elemento a elemento como las siguientes.

### Suma

In [18]:
result_sum = data + other_array
result_sum

array([[11, 22, 33],
       [44, 55, 66]])

### Resta

In [21]:
result_subtract = data - other_array
result_subtract

array([[ -9, -18, -27],
       [-36, -45, -54]])

### Potencia

In [44]:
result_power = data ** 2
result_power

array([[ 1,  4,  9],
       [16, 25, 36]])

### Division

In [43]:
result_division =  data / 2
result_division

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

### Multiplicación por un escalar

In [22]:
scalar = 2
result_scalar_multiply = data * scalar
result_scalar_multiply

array([[ 2,  4,  6],
       [ 8, 10, 12]])

### Transposición de la matriz:


In [26]:
Transpose_array = other_array.T
Transpose_array

array([[10, 40],
       [20, 50],
       [30, 60]])

### Producto de matrices (producto punto):


In [25]:

result_dot_product = np.dot(data, Transpose_array)
result_dot_product

array([[140, 320],
       [320, 770]])

### Shape

In [30]:
columnas, filas = data.shape

print(columnas)
print(filas)

2
3


## Creando ndarrays

In [33]:
data1 = range(100)

In [34]:
arr1 = np.array(data1)

### Algunas funciones de creación de NumPy arrays importantes

1. array y asarray:


In [35]:
# Ejemplo de array
input_list = [1, 2, 3, 4, 5]
arr_from_list = np.array(input_list)
print("Array creado desde lista:", arr_from_list)

# Ejemplo de asarray
input_tuple = (10, 20, 30, 40, 50)
arr_from_tuple = np.asarray(input_tuple)
print("Array creado desde tupla:", arr_from_tuple)

Array creado desde lista: [1 2 3 4 5]
Array creado desde tupla: [10 20 30 40 50]


2. arange:


In [37]:
# Ejemplo de arange
arr_arange = np.arange(1, 11, 2)  # Inicio, fin (no inclusivo), paso
print("Arreglo utilizando arange:", arr_arange)

Arreglo utilizando arange: [1 3 5 7 9]


3. ones y ones_like:

In [38]:
# Ejemplo de ones
shape = (2, 3)
arr_ones = np.ones(shape, dtype=int)
print("Arreglo de unos:", arr_ones)

# Ejemplo de ones_like
existing_array = np.array([[1, 2, 3], [4, 5, 6]])
arr_ones_like = np.ones_like(existing_array)
print("Arreglo de unos con el mismo shape y dtype que el arreglo existente:", arr_ones_like)

Arreglo de unos: [[1 1 1]
 [1 1 1]]
Arreglo de unos con el mismo shape y dtype que el arreglo existente: [[1 1 1]
 [1 1 1]]


3. Zeros y Zeros_like

In [39]:
# Ejemplo de zeros
shape = (3, 4)
arr_zeros = np.zeros(shape, dtype=float)
print("Arreglo de ceros:", arr_zeros)

# Ejemplo de zeros_like
existing_array = np.array([[10, 20], [30, 40]])
arr_zeros_like = np.zeros_like(existing_array)
print("Arreglo de ceros con el mismo shape y dtype que el arreglo existente:", arr_zeros_like)

Arreglo de ceros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Arreglo de ceros con el mismo shape y dtype que el arreglo existente: [[0 0]
 [0 0]]



4. empty y empty_like:


In [40]:
# Ejemplo de empty
shape = (2, 2)
arr_empty = np.empty(shape, dtype=int)
print("Arreglo vacío (con valores no inicializados):", arr_empty)

# Ejemplo de empty_like
existing_array = np.array([[1, 2], [3, 4]])
arr_empty_like = np.empty_like(existing_array)
print("Arreglo vacío con el mismo shape y dtype que el arreglo existente:", arr_empty_like)

Arreglo vacío (con valores no inicializados): [[-1204092880         395]
 [          0           0]]
Arreglo vacío con el mismo shape y dtype que el arreglo existente: [[10 20]
 [30 40]]


5. full y full_like:

In [41]:
# Ejemplo de full
shape = (3, 3)
fill_value = 7
arr_full = np.full(shape, fill_value)
print("Arreglo con valores iguales al valor de relleno:", arr_full)

# Ejemplo de full_like
existing_array = np.array([[5, 10], [15, 20]])
arr_full_like = np.full_like(existing_array, fill_value)
print("Arreglo con valores iguales al valor de relleno y con el mismo shape y dtype que el arreglo existente:", arr_full_like)

Arreglo con valores iguales al valor de relleno: [[7 7 7]
 [7 7 7]
 [7 7 7]]
Arreglo con valores iguales al valor de relleno y con el mismo shape y dtype que el arreglo existente: [[7 7]
 [7 7]]


6. eye e identity:


In [42]:
# Ejemplo de eye
N = 4
arr_eye = np.eye(N)
print("Matriz identidad de 4x4:")
print(arr_eye)

# Ejemplo de identity
M = 3
arr_identity = np.identity(M)
print("Matriz identidad de 3x3:")
print(arr_identity)


Matriz identidad de 4x4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriz identidad de 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Recuerda que en cada ejemplo, debes importar la biblioteca NumPy (import numpy as np) para utilizar estas funciones. Los resultados mostrados son solo ejemplos, y puedes cambiar los valores de entrada o las formas de los arreglos para explorar diferentes situaciones y funcionalidades de NumPy.

## Indexation básica y rebanadas

1. Indexando Arrays Unidimensionales

Para un array unidimensional, el indexado y el slicing funcionan de manera similar a las listas de Python.

In [45]:
a = np.array([0, 1, 2, 3, 4, 5])

# Indexando
print(a[0])  # 0
print(a[4])  # 4

# Slicing
print(a[1:4])  # [1 2 3]
print(a[:3])   # [0 1 2]
print(a[3:])   # [3 4 5]


0
4
[1 2 3]
[0 1 2]
[3 4 5]


2. Indexando Arrays Bidimensionales (Matrices)

Para arrays bidimensionales, puedes pensar en la primera dimensión como "filas" y la segunda como "columnas".

In [47]:
b = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(b)

# Indexando
print(b[0, 0])  # 0
print(b[1, 2])  # 5

# Slicing
print(b[0:2, 1:3])  # [[1 2]
                    #  [4 5]]

print(b[:, 1])      # [1 4 7]


[[0 1 2]
 [3 4 5]
 [6 7 8]]
0
5
[[1 2]
 [4 5]]
[1 4 7]


3. Indexando Arrays Multidimensionales

Para arrays con más de dos dimensiones, el principio es el mismo, solo que se agregan más índices.

In [49]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
print(c)

# Indexando
print(c[0, 1, 1])  # 3

# Slicing
print(c[0, :, 1])  # [1 3]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3
[1 3]
